# How i can add or remove the masks ids? add or remove the id from hidden_masks (if you add a id you need to add a comma). Example: id1,id2 

plugin_configuration:
  hidden_masks: "1048,1270,434,441"
  override_permission: "ss.overridepermission"